### PR TITLE
Update resourceAuthoringChecklist.md

### PR DESCRIPTION
**Pull request by YBoutemy**
Orthographe. Accord de l'adjectif "idempotent" en genre et en nombre.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershell-docs.fr-fr/2)

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/resourceAuthoringChecklist.md](https://github.com/YBoutemy/powerShell-Docs.fr-fr/blob/patch-1/dsc/resourceAuthoringChecklist.md) | :warning:Warning | | [Details](#user-content-dsc/resourceAuthoringChecklist.md)

<a name="dsc/resourceAuthoringChecklist.md"></a>
### [dsc/resourceAuthoringChecklist.md](https://github.com/YBoutemy/powerShell-Docs.fr-fr/blob/patch-1/dsc/resourceAuthoringChecklist.md)
 - **[Warning]** the value HT is undefined for metadata translationtype

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C17%5C96410cf1-dc7e-d7eb-731b-1650bb5e2ad8%5CPullRequest%5C201702171509073628-2%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/resourceAuthoringChecklist.md](https://github.com/YBoutemy/powerShell-Docs.fr-fr/blob/patch-1/dsc/resourceAuthoringChecklist.md) | :warning:Warning | | [Details](#user-content-dsc/resourceAuthoringChecklist.md)

<a name="dsc/resourceAuthoringChecklist.md"></a>
### [dsc/resourceAuthoringChecklist.md](https://github.com/YBoutemy/powerShell-Docs.fr-fr/blob/patch-1/dsc/resourceAuthoringChecklist.md)
 - **[Warning]** the value HT is undefined for metadata translationtype

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C17%5C96410cf1-dc7e-d7eb-731b-1650bb5e2ad8%5CPullRequest%5C201702171510156693-2%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Bonjour @YBoutemy , vos commentaires font toujours l’objet de discussions. Nous mettrons bientôt à jour la décision correspondante.  
	 
Nous vous remercions pour votre soutien, 
L’équipe de localisation C&E Microsoft

**Comment by v-radelg** [comment]
Bonjour @YBoutemy  merci pour vos commentaires et vos suggestions.  
	 
Votre suggestion sera intégrée à la production. Nous publierons à nouveau ces articles dans la prochaine version localisée.  
	 
L’équipe de localisation C&E Microsoft

**Pull request merged**
